fixed issues and better naming

diff --git a/scripts/services-systemd b/scripts/services-systemd
--- a/scripts/services-systemd
+++ b/scripts/services-systemd
@@ -5,11 +5,16 @@
 # ==============================================================================
 
 # Source functions
-FUNCTIONS_DIR="$HOME/dotfiles/scripts/.setup/functions/"
-# shellcheck source=/dev/null
-source "$FUNCTIONS_DIR/service-management-functions"
-# shellcheck source=/dev/null
-source "$FUNCTIONS_DIR/environment-specific-services"
+FUNCTIONS_DIR="$HOME/dotfiles/scripts/.setup/lib"
+if [[ -d "$FUNCTIONS_DIR" ]] ; then
+    # shellcheck source=/dev/null
+    source "$FUNCTIONS_DIR/services-systemd-functions"
+    # shellcheck source=/dev/null
+    source "$FUNCTIONS_DIR/environment-specific-services"
+else
+    error "Could not import functions from $FUNCTIONS_DIR"
+    exit 1
+fi
 
 # ==============================================================================
 #  Initialization
@@ -55,7 +60,6 @@ header "Systemd timer configuration"
 
 # Enable distro-specific timers
 configure_arch_timers
-
 
 # Systemd user
 run_task "Enabling failed systemd service check timer" systemctl --user enable --now failed-units-check.timer
diff --git a/scripts/setup b/scripts/setup
--- a/scripts/setup
+++ b/scripts/setup
@@ -5,15 +5,20 @@ set -e
 set -o pipefail
 
 # Source functions
-FUNCTIONS_DIR="$HOME/dotfiles/scripts/.setup/functions"
-# shellcheck source=/dev/null
-source "$FUNCTIONS_DIR/setup-functions"
+FUNCTIONS_DIR="$HOME/dotfiles/scripts/.setup/lib"
+if [[ -d "$FUNCTIONS_DIR" ]]; then
+    # shellcheck source=/dev/null
+    source "$FUNCTIONS_DIR/setup-functions"
+else 
+    error "Could not import functions from $FUNCTIONS_DIR"
+    exit 1
+fi
 
 # Import functions
 check_if_root         # Ensure user doesnt run this as root
 keep_sudo_alive       # Keep sudo active for the duration of the script
 xdg_setup             # Setup xdg directory structure
-import_setup_scripts  # Import setup scripts
+prepare_setup_scripts # Prepare setup scripts with chmod u+x
 import_package_list   # Import the package list
 
 # --- USER INTERACTION ---
